global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'zappy-api'
    static_configs:
      - targets: ['api:5000']
  
  - job_name: 'zappy-webhook'
    static_configs:
      - targets: ['webhook:5001']
